name: build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Setting up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cargo install
        working-directory: ./src-tauri
        run: cargo install | cargo install tauri-cli --version "^2.0.0" --locked
      - name: Build app
        working-directory: ./src-tauri
        run: cargo tauri build --bundles app
#      - name: Create Release
#        uses: actions/create-release@v1
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false