name: build
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Setting up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri"
          shared-key: "macos_build"
      - name: Setup Tauri CLI
        working-directory: ./src-tauri
        run: cargo install tauri-cli --version "^2.0.0" --locked
      - name: Setup Next CLi
        run: npm install next-cli
      - name: Build app
        working-directory: ./src-tauri
        run: cargo tauri build --bundles app
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          body: Updates made
          files: ./src-tauri/target/release/bundle/macos/YakClient.app
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Setting up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri"
          shared-key: "windows_build"
      - name: Setup Tauri CLI
        working-directory: ./src-tauri
        run: cargo install tauri-cli --version "^2.0.0" --locked
      - name: Setup Next CLi
        run: npm install next-cli
      - name: Build app
        working-directory: ./src-tauri
        run: cargo tauri build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          body: Updates made
          files: ./src-tauri/target/release/bundle/msi/YakClient_1.0.6_arm64_en-US.msi
